import type { ComponentType } from 'react'
import {
  Workflow, Target, Handshake, UserCog, CreditCard, Mail, Shield, Landmark,
  MailWarning, ListChecks, BadgeCheck, CircleUser, BarChart2, Calculator, FileText,
  Star, Calendar, Users, Building2, LayoutGrid, FileSpreadsheet, Layers,
  Truck, Factory, Cpu, Store, Briefcase, HardHat, Radio, GraduationCap,
  Headphones, Receipt, CalendarDays, ClipboardCheck, Database, FolderKanban,
  FileSignature,
} from 'lucide-react'

export type FaqCategoria = 'Comercial' | 'Fiscal' | 'Operacional' | 'Cadastros e estrutura' | 'Trabalhista' | 'Templates por Segmento'

export interface FaqArtigo {
  slug: string
  titulo: string
  descricao: string
  modulo: string
  moduloColor: string
  icon: ComponentType<{ className?: string }>
  categoria: FaqCategoria
  /** false = artigo planejado mas ainda não escrito; sai do índice até estar pronto */
  disponivel: boolean
  tags: string[]
}

// Lista única de artigos. Para adicionar um novo:
//   1. Crie a página em /faq/<slug>/page.tsx
//   2. Acrescente entrada aqui com disponivel: true
export const FAQ_ARTIGOS: FaqArtigo[] = [
  // ─── Comercial ───────────────────────────────────────────────
  {
    slug: 'orcamentos',
    titulo: 'Orçamentos: do NOVO ao FINALIZADO',
    descricao: 'Fluxo completo da proposta comercial — criação, itens, envio ao cliente, aprovação pública, execução automática e fechamento com pesquisa NPS.',
    modulo: 'Orçamentos',
    moduloColor: '#fb7185',
    icon: FileSignature,
    categoria: 'Comercial',
    disponivel: true,
    tags: ['orçamento', 'proposta', 'fsm', 'aprovação', 'link público', 'kanban', 'envio', 'pesquisa nps', 'reabrir', 'paralisar'],
  },
  {
    slug: 'orcamentos-notificacoes-email',
    titulo: 'Orçamentos: notificações por e-mail e sino',
    descricao: 'Quem é avisado, por qual canal e em qual passo do orçamento — áreas, envio ao cliente, aprovação, liberação, finalização e atrasos — e o que cada configuração controla.',
    modulo: 'Orçamentos',
    moduloColor: '#fb7185',
    icon: Mail,
    categoria: 'Comercial',
    disponivel: true,
    tags: ['orçamento', 'notificação', 'e-mail', 'sino', 'comercial', 'financeiro', 'áreas', 'atraso', 'sla', 'configuração'],
  },
  {
    slug: 'processos',
    titulo: 'Fluxo de Processos: do orçamento à conclusão',
    descricao: 'Como configurar templates encadeados, aprovar orçamentos que disparam processos automáticos e gerenciar pendências.',
    modulo: 'Processos',
    moduloColor: '#8b5cf6',
    icon: Workflow,
    categoria: 'Comercial',
    disponivel: true,
    tags: ['processos', 'orçamento', 'serviços', 'encadeamento', 'transferência', 'constituição'],
  },
  {
    slug: 'crm-pipeline',
    titulo: 'CRM: pipeline comercial do lead ao fechamento',
    descricao: 'Operação do funil — etapas, oportunidades, conversão em orçamento e fechamento ganho/perdido.',
    modulo: 'CRM',
    moduloColor: '#fb7185',
    icon: Target,
    categoria: 'Comercial',
    disponivel: true,
    tags: ['crm', 'pipeline', 'funil', 'lead', 'oportunidade'],
  },
  {
    slug: 'cliente-onboard',
    titulo: 'Cliente: cadastro, áreas contratadas e responsáveis',
    descricao: 'Cadastro completo de cliente — do CNPJ ao contrato, definindo áreas, responsáveis e contatos.',
    modulo: 'Clientes',
    moduloColor: '#10b981',
    icon: Handshake,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['cliente', 'cadastro', 'cnpj', 'áreas', 'responsável'],
  },
  {
    slug: 'tenant-stripe-setup',
    titulo: 'Configuração inicial: certificado digital e Stripe',
    descricao: 'Setup do tenant — empresa, certificado A1, plano de assinatura Stripe e usuário master.',
    modulo: 'Configurações',
    moduloColor: '#f97316',
    icon: CreditCard,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['stripe', 'certificado', 'tenant', 'master', 'configuração inicial'],
  },
  {
    slug: 'usuario-mfa-permissoes',
    titulo: 'Usuários: convite, MFA e permissões',
    descricao: 'Como convidar novos usuários, exigir MFA (TOTP) e configurar permissões granulares por módulo.',
    modulo: 'Usuários',
    moduloColor: '#10b981',
    icon: UserCog,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['usuário', 'mfa', 'totp', 'permissão', 'rbac', 'convite'],
  },
  {
    slug: 'contratos',
    titulo: 'Contratos: cláusulas, modelos e geração',
    descricao: 'Como montar modelos de contrato com cláusulas reutilizáveis e gerar contratos para clientes.',
    modulo: 'Contratos',
    moduloColor: '#fb7185',
    icon: FileText,
    categoria: 'Comercial',
    disponivel: true,
    tags: ['contrato', 'cláusula', 'modelo', 'gerar'],
  },
  {
    slug: 'pesquisa-satisfacao',
    titulo: 'Pesquisa de Satisfação: NPS e respostas',
    descricao: 'Disparo automático ao finalizar orçamento, link público de resposta e análise de NPS.',
    modulo: 'Pesquisas',
    moduloColor: '#fb7185',
    icon: Star,
    categoria: 'Comercial',
    disponivel: true,
    tags: ['nps', 'pesquisa', 'satisfação', 'pós-venda'],
  },

  // ─── Fiscal ──────────────────────────────────────────────────
  {
    slug: 'caixapostal-ecac',
    titulo: 'Caixa Postal e-CAC: agendamento, leitura e alertas',
    descricao: 'Configurar consulta automática, ler mensagens, marcar importantes e receber alertas P0/P1.',
    modulo: 'Caixa Postal',
    moduloColor: '#0ea5e9',
    icon: Mail,
    categoria: 'Fiscal',
    disponivel: true,
    tags: ['caixa postal', 'e-cac', 'mensagens', 'alertas'],
  },
  {
    slug: 'cnds-federais',
    titulo: 'CND Federais: consulta automática e expiração',
    descricao: 'Agendamento de consulta de CNDs federais, alertas de vencimento e download em lote.',
    modulo: 'Certidões',
    moduloColor: '#6366f1',
    icon: Shield,
    categoria: 'Fiscal',
    disponivel: true,
    tags: ['cnd', 'certidão', 'receita federal', 'fgts', 'cndt'],
  },
  {
    slug: 'cnds-estaduais-municipais',
    titulo: 'CND Estaduais e Municipais e Alvarás',
    descricao: 'Consulta de certidões estaduais (SEFAZ), municipais (ISS) e alvarás (Bombeiros/Funcionamento).',
    modulo: 'Certidões',
    moduloColor: '#8b5cf6',
    icon: Landmark,
    categoria: 'Fiscal',
    disponivel: true,
    tags: ['cnd', 'sefaz', 'iss', 'alvará', 'bombeiros'],
  },
  {
    slug: 'dte-sefaz-es',
    titulo: 'DT-e SEFAZ ES: setup e monitoramento',
    descricao: 'Configurar acesso (Cidadão→gov.br→cert PF→Agência Virtual) e monitorar mensagens da SEFAZ.',
    modulo: 'DT-e',
    moduloColor: '#818cf8',
    icon: MailWarning,
    categoria: 'Fiscal',
    disponivel: true,
    tags: ['dt-e', 'sefaz', 'es', 'acesso cidadão', 'gov.br'],
  },
  {
    slug: 'dctfweb',
    titulo: 'DCTFWeb: importação e conferência mensal',
    descricao: 'Importar relatório DCTFWeb, conferir débitos e marcar competências como conciliadas.',
    modulo: 'DCTFWeb',
    moduloColor: '#0ea5e9',
    icon: ListChecks,
    categoria: 'Fiscal',
    disponivel: true,
    tags: ['dctfweb', 'declaração', 'débitos', 'mensal'],
  },
  {
    slug: 'gestao-certificados',
    titulo: 'Certificados Digitais: cadastro, importação e uso',
    descricao: 'Cadastrar certificados A1 (PFX), importar em lote da V1 e renovar antes do vencimento.',
    modulo: 'Certificados Digitais',
    moduloColor: '#e879f9',
    icon: BadgeCheck,
    categoria: 'Fiscal',
    disponivel: true,
    tags: ['certificado', 'a1', 'pfx', 'icp-brasil', 'renovação'],
  },
  {
    slug: 'situacao-fiscal',
    titulo: 'Situação Fiscal: relatório SERPRO',
    descricao: 'Consultar relatório de Situação Fiscal SERPRO para clientes, identificar pendências.',
    modulo: 'Situação Fiscal',
    moduloColor: '#0ea5e9',
    icon: CircleUser,
    categoria: 'Fiscal',
    disponivel: true,
    tags: ['situação fiscal', 'serpro', 'pendências'],
  },

  // ─── Operacional ─────────────────────────────────────────────
  {
    slug: 'servicos-notificacoes',
    titulo: 'Recorrência e notificações automáticas por serviço',
    descricao: 'Configurar disparo periódico (mensal/anual) e regras de e-mail por evento (atrasada, concluída, prazo próximo etc).',
    modulo: 'Serviços',
    moduloColor: '#10b981',
    icon: Mail,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['serviços', 'notificações', 'e-mail', 'recorrência', 'cron', 'automatização', 'sla'],
  },
  {
    slug: 'servicos-editor',
    titulo: 'Serviços: editor de fluxograma e bloco Decisão',
    descricao: 'Como modelar a cadeia de serviços visualmente — criar/editar/excluir ligações, arrastar blocos, blocos de decisão e auto-organizar.',
    modulo: 'Serviços',
    moduloColor: '#10b981',
    icon: Workflow,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['serviços', 'fluxograma', 'fluxo', 'react-flow', 'decisão', 'encadeamento'],
  },
  {
    slug: 'helpdesk',
    titulo: 'HelpDesk: abertura, atendimento, SLA e CSAT',
    descricao: 'Fluxo completo do ticket — do registro pelo solicitante (interno ou por e-mail) ao fechamento com avaliação.',
    modulo: 'HelpDesk',
    moduloColor: '#22d3ee',
    icon: Headphones,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['helpdesk', 'ticket', 'sla', 'csat', 'ti', 'kanban', 'suporte'],
  },
  {
    slug: 'controle-ativos',
    titulo: 'Gestão de Ativos: cadastro, atribuição, manutenção e inventário',
    descricao: 'Patrimônio de TI/mobiliário — cadastro com QR code, atribuição a colaboradores, manutenções, depreciação e termo de responsabilidade.',
    modulo: 'Gestão de Ativos',
    moduloColor: '#0ea5e9',
    icon: Database,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['ativos', 'patrimônio', 'ti', 'inventário', 'qr code', 'manutenção', 'depreciação', 'termo de responsabilidade'],
  },
  {
    slug: 'projetos',
    titulo: 'Projetos: gestão de desenvolvimento da TI',
    descricao: 'Como cadastrar projetos, acompanhar tarefas em lista ou Kanban, registrar andamentos e anexar arquivos. Bloco TI — uso interno do time de TI.',
    modulo: 'Projetos',
    moduloColor: '#5ea3cb',
    icon: FolderKanban,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['projetos', 'kanban', 'tarefas', 'ti', 'desenvolvimento', 'roadmap', 'backlog', 'anexos', 'comentários'],
  },
  {
    slug: 'meus-servicos',
    titulo: 'Meus Serviços: checklist, SLAs, pausa e arquivamento',
    descricao: 'Painel do operador — concluir passos, pausar quando aguardando cliente, arquivar concluídos.',
    modulo: 'Meus Serviços',
    moduloColor: '#0ea5e9',
    icon: ListChecks,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['meus serviços', 'checklist', 'sla', 'pausa', 'execução'],
  },
  {
    slug: 'minhas-obrigacoes',
    titulo: 'Minhas Obrigações: painel pessoal de entregas',
    descricao: 'Lista, calendário e fluxo de entrega das obrigações sob sua responsabilidade — com log e histórico completos.',
    modulo: 'Minhas Obrigações',
    moduloColor: '#0ea5e9',
    icon: ClipboardCheck,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['minhas obrigações', 'entrega', 'fiscal', 'acessória', 'calendário', 'log'],
  },
  {
    slug: 'bi-faturamento',
    titulo: 'BI Faturamento: KPIs, balancete e dashboard financeiro',
    descricao: 'Como o sistema importa balancete do SCI, calcula KPIs e exibe gráficos por cliente.',
    modulo: 'BI',
    moduloColor: '#8b5cf6',
    icon: BarChart2,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['bi', 'kpi', 'balancete', 'sci', 'faturamento'],
  },
  {
    slug: 'bi-categorias-balancete',
    titulo: 'Categorias de Balancete: regras de cálculo e KPIs',
    descricao: 'Configurar agrupamento de contas do balancete em categorias para alimentar KPIs do BI.',
    modulo: 'BI',
    moduloColor: '#8b5cf6',
    icon: Calculator,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['categoria', 'balancete', 'kpi', 'conta'],
  },
  {
    slug: 'agenda-corporativa',
    titulo: 'Agenda Corporativa: eventos e Google Calendar',
    descricao: 'Criar eventos, convidar participantes, integrar com Google Calendar via OAuth.',
    modulo: 'Agenda',
    moduloColor: '#0ea5e9',
    icon: Calendar,
    categoria: 'Operacional',
    disponivel: true,
    tags: ['agenda', 'evento', 'google calendar', 'oauth'],
  },

  // ─── Trabalhista ─────────────────────────────────────────────
  {
    slug: 'folha-pagamento',
    titulo: 'Importação de Folha de Pagamento',
    descricao: 'Importar arquivos de folha mensal e configurar mapeamento de eventos em filiais.',
    modulo: 'Folha',
    moduloColor: '#8b5cf6',
    icon: FileSpreadsheet,
    categoria: 'Trabalhista',
    disponivel: true,
    tags: ['folha', 'eventos', 'filial', 'importação'],
  },

  // ─── Cadastros e estrutura ───────────────────────────────────
  {
    slug: 'calendario-feriados',
    titulo: 'Calendário de feriados estaduais e municipais',
    descricao: 'Cadastro de feriados estaduais, municipais e pontos facultativos — base para futuro ajuste automático de vencimento por UF/cidade.',
    modulo: 'Calendário',
    moduloColor: '#f97316',
    icon: CalendarDays,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['feriado', 'calendário', 'estadual', 'municipal', 'ponto facultativo', 'es', 'grande vitória'],
  },
  {
    slug: 'obrigacoes',
    titulo: 'Obrigações Acessórias: catálogo, vencimentos e fontes oficiais',
    descricao: 'Templates globais de obrigações fiscais, trabalhistas e contábeis com regra de recorrência, vencimento previsto e link para fonte legal + documentação.',
    modulo: 'Obrigações',
    moduloColor: '#10b981',
    icon: Receipt,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['obrigações', 'acessórias', 'fiscal', 'trabalhista', 'contábil', 'das', 'dctfweb', 'esocial', 'vencimento', 'recorrência'],
  },
  {
    slug: 'areas-cargos-lideres',
    titulo: 'Áreas, Cargos e Líderes: hierarquia organizacional',
    descricao: 'Como áreas, cargos e líderes definem visibilidade de execuções e contratações por cliente.',
    modulo: 'Cadastros',
    moduloColor: '#10b981',
    icon: Users,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['área', 'cargo', 'líder', 'hierarquia', 'visibilidade'],
  },
  {
    slug: 'multi-empresa',
    titulo: 'Multi-empresa: scope e permissões cruzadas',
    descricao: 'Como o sistema separa dados por empresa dentro do mesmo tenant e quando dados são compartilhados.',
    modulo: 'Empresas',
    moduloColor: '#10b981',
    icon: Building2,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['multi-empresa', 'scope', 'tenant'],
  },
  {
    slug: 'dashboard-customizado',
    titulo: 'Dashboard customizado: widgets e layout',
    descricao: 'Adicionar/remover widgets, personalizar título, expandir em modal, salvar layout por empresa.',
    modulo: 'Dashboard',
    moduloColor: '#0ea5e9',
    icon: LayoutGrid,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['dashboard', 'widget', 'layout', 'customização'],
  },
  {
    slug: 'tabs-fixacao',
    titulo: 'Sistema de Abas: navegação rápida e fixação',
    descricao: 'Como abrir múltiplas páginas em abas, fixar as importantes, fechar em massa e reordenar.',
    modulo: 'Navegação',
    moduloColor: '#10b981',
    icon: Layers,
    categoria: 'Cadastros e estrutura',
    disponivel: true,
    tags: ['tabs', 'abas', 'fixar', 'pinar', 'navegação'],
  },

  // ─── Templates por Segmento ──────────────────────────────────
  {
    slug: 'segmento-atacadista-lucro-real',
    titulo: 'Atacadista / Distribuidor / Importador (Lucro Real)',
    descricao: 'Templates de processo para atacadistas LR — onboarding, fechamento mensal (ICMS-ST, EFD-ICMS/IPI, EFD-Contribuições) e anual (ECD/ECF).',
    modulo: 'Atacadista LR',
    moduloColor: '#0ea5e9',
    icon: Truck,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['atacadista', 'distribuidor', 'importador', 'lucro real', 'compete-es', 'icms-st'],
  },
  {
    slug: 'segmento-industria-lucro-real',
    titulo: 'Indústria / Manufatura (Lucro Real + Bloco K)',
    descricao: 'Templates para indústrias LR — controle de produção (Bloco K), apuração ICMS+IPI, EFD-ICMS/IPI integrada.',
    modulo: 'Indústria LR',
    moduloColor: '#fb7185',
    icon: Factory,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['indústria', 'manufatura', 'bloco k', 'ipi', 'lucro real'],
  },
  {
    slug: 'segmento-tecnologia-presumido',
    titulo: 'Tecnologia / SaaS (Lucro Presumido)',
    descricao: 'Templates para empresas Tech Presumido — ISS, PIS/COFINS cumulativo, IRPJ trimestral 32%, Lei do Bem opcional.',
    modulo: 'Tech Presumido',
    moduloColor: '#8b5cf6',
    icon: Cpu,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['tecnologia', 'saas', 'lucro presumido', 'iss', 'lei do bem'],
  },
  {
    slug: 'segmento-tecnologia-real',
    titulo: 'Tecnologia / SaaS (Lucro Real)',
    descricao: 'Templates para empresas Tech LR — PIS/COFINS não-cumulativo com créditos amplos sobre cloud e licenças.',
    modulo: 'Tech Real',
    moduloColor: '#8b5cf6',
    icon: Cpu,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['tecnologia', 'saas', 'lucro real', 'créditos pis cofins'],
  },
  {
    slug: 'segmento-comercio-varejo-simples',
    titulo: 'Comércio Varejo (Simples Nacional)',
    descricao: 'Templates Simples — DAS único, DEFIS anual, NFC-e, DeSTDA mensal.',
    modulo: 'Varejo Simples',
    moduloColor: '#10b981',
    icon: Store,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['varejo', 'simples nacional', 'das', 'defis', 'nfc-e', 'destda'],
  },
  {
    slug: 'segmento-holding-presumido',
    titulo: 'Holding / Participações (Lucro Presumido)',
    descricao: 'Templates para Holdings — rotina enxuta com MEP (equivalência patrimonial) e distribuição de lucros isenta.',
    modulo: 'Holding',
    moduloColor: '#6366f1',
    icon: Briefcase,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['holding', 'participações', 'mep', 'distribuição lucros'],
  },
  {
    slug: 'segmento-construcao-civil-presumido',
    titulo: 'Construção Civil (Lucro Presumido)',
    descricao: 'Templates para construtoras — presunção 8%, RET, retenção INSS 3,5%, ISS por obra/município.',
    modulo: 'Construção',
    moduloColor: '#f59e0b',
    icon: HardHat,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['construção civil', 'lucro presumido', 'ret', 'cei', 'iss obra'],
  },
  {
    slug: 'segmento-telecomunicacoes-lucro-real',
    titulo: 'Telecomunicações (Lucro Real)',
    descricao: 'Templates para operadoras telecom — ICMS-Comunicação, FUST, FUNTTEL, CFRP, Convênio 126/1998.',
    modulo: 'Telecom',
    moduloColor: '#818cf8',
    icon: Radio,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['telecomunicações', 'icms comunicação', 'anatel', 'fust', 'funttel'],
  },
  {
    slug: 'segmento-educacao-presumido',
    titulo: 'Educação (Lucro Presumido)',
    descricao: 'Templates para escolas/idiomas — ISS reduzido (Vitória 2%), avaliação de imunidade tributária, alta carga de folha.',
    modulo: 'Educação',
    moduloColor: '#d946ef',
    icon: GraduationCap,
    categoria: 'Templates por Segmento',
    disponivel: true,
    tags: ['educação', 'escolas', 'idiomas', 'iss reduzido', 'imunidade tributária'],
  },
]

export const CATEGORIA_ORDEM: FaqCategoria[] = [
  'Comercial',
  'Fiscal',
  'Operacional',
  'Trabalhista',
  'Cadastros e estrutura',
  'Templates por Segmento',
]
