import { Module } from '@nestjs/common'
import { TrpcService } from './trpc.service'
import { TrpcController } from './trpc.controller'
import { AreaModule } from '../area/area.module'
import { EmpresaModule } from '../empresa/empresa.module'
import { UserModule } from '../user/user.module'
import { CargoModule } from '../cargo/cargo.module'
import { OnboardingModule } from '../onboarding/onboarding.module'
import { AdminModule } from '../admin/admin.module'
import { AdminTenantModule } from '../admin-tenant/admin-tenant.module'
import { ClienteModule } from '../cliente/cliente.module'
import { AuthModule } from '../auth/auth.module'
import { StripeModule } from '../stripe/stripe.module'
import { ColaboradorModule } from '../colaborador/colaborador.module'
import { FornecedorModule } from '../fornecedor/fornecedor.module'
import { SocioModule } from '../socio/socio.module'
import { CnpjModule } from '../cnpj/cnpj.module'
import { SitfisModule } from '../sitfis/sitfis.module'
import { CaixaPostalModule } from '../caixapostal/caixapostal.module'
import { CndModule } from '../cnd/cnd.module'
import { DctfwebModule } from '../dctfweb/dctfweb.module'
import { BiModule } from '../bi/bi.module'
import { FolhaModule } from '../folha/folha.module'
import { AgendaModule } from '../agenda/agenda.module'
import { DteModule } from '../dte/dte.module'
import { CrmModule } from '../crm/crm.module'
import { OrcamentoModule } from '../orcamento/orcamento.module'
import { BeneficioFiscalModule } from '../beneficio-fiscal/beneficio-fiscal.module'
import { NotaModule } from '../nota/nota.module'
import { WhatsappModule } from '../whatsapp/whatsapp.module'
import { FaqModule } from '../faq/faq.module'
import { ServicoModule } from '../servico/servico.module'
import { ProcessoModule } from '../processo/processo.module'
import { PesquisaModule } from '../pesquisa/pesquisa.module'
import { ContratoModule } from '../contrato/contrato.module'
import { NotificationModule } from '../notification/notification.module'
import { TabsModule } from '../tabs/tabs.module'
import { CertificadoDigitalModule } from '../certificado-digital/certificado-digital.module'
import { DashboardLayoutModule } from '../dashboard-layout/dashboard-layout.module'
import { PermissionsEventsModule } from '../permissions-events/permissions-events.module'
import { NotificationsEventsModule } from '../notifications-events/notifications-events.module'
import { DashboardCalendarioModule } from '../dashboard-calendario/dashboard-calendario.module'
import { HelpdeskModule } from '../helpdesk/helpdesk.module'
import { LeadModule } from '../lead/lead.module'
import { BeneficioModule } from '../beneficio/beneficio.module'
import { PainelTvModule } from '../painel-tv/painel-tv.module'
import { AcessoriasModule } from '../acessorias/acessorias.module'
import { NotificacaoModule } from '../notificacao/notificacao.module'
import { ObrigacaoModule } from '../obrigacao/obrigacao.module'
import { FeriadoModule } from '../feriado/feriado.module'
import { GrupoObrigacaoModule } from '../grupo-obrigacao/grupo-obrigacao.module'
import { ProjetoModule } from '../projeto/projeto.module'
import { MinhasObrigacoesModule } from '../minhas-obrigacoes/minhas-obrigacoes.module'
import { AtivoModule } from '../ativo/ativo.module'
import { ClientErrorModule } from '../client-error/client-error.module'
import { ThemeModule } from '../theme/theme.module'
import { DanfeModule } from '../danfe/danfe.module'
import { DriveSyncModule } from '../drive-sync/drive-sync.module'
import { NfeDistModule } from '../nfe-dist/nfe-dist.module'
import { NfseDistModule } from '../nfse-dist/nfse-dist.module'
import { AgendamentoModule } from '../agendamento/agendamento.module'
import { GoogleBackupModule } from '../google-backup/google-backup.module'
import { SignatureModule } from '../signature/signature.module'
import { OnlineUsersModule } from '../online-users/online-users.module'
import { ChatModule } from '../chat/chat.module'
import { PushModule } from '../push/push.module'

@Module({
  imports: [AreaModule, EmpresaModule, UserModule, CargoModule, OnboardingModule, ClienteModule, AdminModule, AdminTenantModule, AuthModule, StripeModule, ColaboradorModule, FornecedorModule, SocioModule, CnpjModule, SitfisModule, CaixaPostalModule, CndModule, DctfwebModule, BiModule, FolhaModule, AgendaModule, DteModule, CrmModule, OrcamentoModule, BeneficioFiscalModule, NotaModule, WhatsappModule, FaqModule, ServicoModule, ProcessoModule, PesquisaModule, ContratoModule, NotificationModule, TabsModule, CertificadoDigitalModule, DashboardLayoutModule, PermissionsEventsModule, NotificationsEventsModule, DashboardCalendarioModule, HelpdeskModule, AcessoriasModule, NotificacaoModule, ObrigacaoModule, FeriadoModule, GrupoObrigacaoModule, ProjetoModule, MinhasObrigacoesModule, AtivoModule, ClientErrorModule, ThemeModule, DanfeModule, DriveSyncModule, NfeDistModule, NfseDistModule, AgendamentoModule, GoogleBackupModule, SignatureModule, OnlineUsersModule, ChatModule, PushModule, PainelTvModule, LeadModule, BeneficioModule],
  providers: [TrpcService],
  controllers: [TrpcController],
  exports: [TrpcService],
})
export class TrpcModule {}
