-- ============================================================
-- Relatório de QA — auditoria do módulo /clientes (backend core + integrações
-- + frontend), 06/07/2026. Seed guardado (NOT EXISTS qa_cli26_%). Idempotente.
-- Achados VERIFICADOS no código; padrões repetidos consolidados num item.
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM qa_itens WHERE id LIKE 'qa_cli26_%') THEN
    INSERT INTO qa_itens (id, modulo, severidade, titulo, descricao, arquivo, fix_proposto, origem) VALUES
    ('qa_cli26_a1', 'clientes', 'ALTA', 'IDOR multi-tenant nos sub-recursos do cliente (arquivos, contatos, inscrições, atividades, benefícios, vencimentos, andamentos, CNAEs)',
     'O router gateia por PERMISSÃO DE MÓDULO (writeSubProcedure clientes+sub-perm), mas os métodos add/update/remove de sub-recursos NÃO recebem empresaId nem validam o tenant do registro. Um não-master com a sub-perm, informando um clienteId/arquivoId/contatoId de OUTRA empresa, cria/edita/exclui em cliente de outro tenant. ~17 métodos com o mesmo padrão. Hoje o risco prático é baixo (org única), mas é falha real pra multi-tenant.',
     'apps/api/src/cliente/cliente.service.ts:534-664 (arquivos/contatos) · 585-634 (inscrições/atividades/benefícios) · 1198-1266 (vencimentos/andamentos/cnaes)',
     'Validar o tenant do cliente dono antes de cada mutação (getById(clienteId,isMaster,empresaId) ou WHERE cliente.empresaId=$emp) — idealmente um helper assertClienteTenant reusável.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_a2', 'clientes', 'ALTA', 'Sub-recursos podem ser modificados em cliente na LIXEIRA (soft-delete bypass)',
     'Nenhuma mutação de sub-recurso (arquivos/contatos/atividades/benefícios/inscrições/vencimentos/andamentos) checa cliente.deletedAt IS NULL — dá pra alterar dados de um cliente já inativado/na lixeira.',
     'apps/api/src/cliente/cliente.service.ts (todas as mutações de sub-recurso)',
     'Junto com o assert de tenant, exigir deletedAt IS NULL (bloquear mutação em cliente da lixeira).',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_a3', 'clientes', 'ALTA', 'Dark mode quebrado: hex/rgba hardcoded no cadastro do cliente',
     'CLAUDE.md proíbe hex hardcoded (quebra dark mode). O módulo tem ~30x border-[rgba(0,0,0,0.08)] (some no escuro), backgroundColor:#10b981 nas abas, bg-[#5ea3cb]/#4d8fb5 no botão CNPJ, #0b1020 no integrações-modal, e paletas inline em contrato-charts. Cores dinâmicas vindas do banco são OK; estas são estáticas.',
     'apps/web/src/app/(dashboard)/clientes/_components/cliente-form.tsx (31 ocorrências) · legalizacao-card.tsx (12) · contrato-charts.tsx · integracoes-modal.tsx · page.tsx',
     'Trocar por tokens semânticos (border-border, bg-muted/40, text-foreground) e classes tailwind com variante dark; manter só as cores dinâmicas do banco.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_m1', 'clientes', 'MEDIA', 'Import OneClick/legado sem transação por cliente — registro meio-importado em caso de erro',
     'integration.service.ts e legacy-import.service.ts processam cliente + sócios + áreas + inscrições em etapas soltas; erro no meio deixa o cliente parcialmente importado. Vários .catch(()=>{}) silenciosos escondem qual cliente falhou.',
     'apps/api/src/cliente/integration.service.ts:437-708 · legacy-import.service.ts:156-177 · import-oneclick.service.ts:162-207',
     'Envolver o processamento de cada cliente em prisma.$transaction e acumular {doc, erro} num relatório em vez de engolir o catch.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_m2', 'clientes', 'MEDIA', 'Import legado casa documento por contains (match falso entre CNPJs)',
     'legacy-import busca cliente existente com documento: { contains: documento } — "12345" casa "12345678901234", podendo atualizar o cliente errado.',
     'apps/api/src/cliente/legacy-import.service.ts:117',
     'Trocar por equals do documento normalizado (11/14 dígitos).',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_m3', 'clientes', 'MEDIA', 'stderr do script Python (SCI/Firebird) devolvido ao usuário',
     'sci.service lança Error com o stderr do script — pode expor detalhes de conexão/SQL do Firebird na tela.',
     'apps/api/src/cliente/sci.service.ts:60-72',
     'Logar o stderr internamente e devolver mensagem genérica ao usuário.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_m4', 'clientes', 'MEDIA', 'Consulta SERPRO em massa sem lock — 2 execuções simultâneas furam o gate de custo',
     'O loop de enriquecimento tem sleep entre clientes, mas duas chamadas paralelas (2 usuários / 2 abas) rodam 2 loops = 2x custo, sem semáforo por empresa.',
     'apps/api/src/cliente/integration.service.ts:114-126',
     'Lock por empresa (mutex em memória ou flag "job em andamento" no banco) impedindo execução concorrente.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_m5', 'clientes', 'MEDIA', 'Datas com off-by-one no cadastro do cliente (front)',
     'Vários toISOString().slice(0,10) sobre datas sem forçar UTC (data de entrada, vencimento de benefício ao editar, encerramento de serviço, vencimento em legalização) — inconsistente com o bfFmtData que usa timeZone:UTC; pode exibir/salvar o dia errado.',
     'apps/web/.../clientes/[id]/page.tsx:40-41 · cliente-form.tsx:3162 · servicos-card.tsx:593 · legalizacao-card.tsx:283',
     'Padronizar num helper (forçar UTC / timeZone:UTC) como já feito no bfFmtData.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_m6', 'clientes', 'MEDIA', 'getContratoParams ignora tenant quando empresaId é undefined',
     'findFirst com ...(empresaId ? {empresaId} : {}) — sem empresaId, retorna params por clienteId sem filtrar empresa (potencial cross-tenant se chamado sem o contexto).',
     'apps/api/src/cliente/cliente.service.ts:687-693',
     'Exigir empresaId no where (ou validar o tenant do clienteId antes).',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_b1', 'clientes', 'BAIXA', 'updateAndamentoStatus interpola NOW()/NULL na string SQL',
     'data_conclusao = ${dataConclusao} monta a query por template string (o valor é controlado — NOW() ou NULL — então não há injection hoje, mas é padrão frágil).',
     'apps/api/src/cliente/cliente.service.ts:1228-1233',
     'Usar CASE WHEN $n = ''concluido'' THEN NOW() ELSE data_conclusao END parametrizado.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_b2', 'clientes', 'BAIXA', 'CNPJ/CPF aceito sem validar dígito verificador',
     'create valida só o comprimento (14/11) — documentos inválidos (ex.: 00000000000000) passam.',
     'apps/api/src/cliente/cliente.service.ts:326',
     'Validar DV via CnpjService/mod11 no create/update.',
     'Auditoria /clientes 06/07/2026'),
    ('qa_cli26_b3', 'clientes', 'BAIXA', 'biImportLinhas faz upsert 1-a-1 em loop (I/O em importação grande)',
     'Upsert individual num for — em importação grande gera muita ida ao banco.',
     'apps/api/src/cliente/cliente.service.ts:1386-1399',
     'deleteMany + createMany em lote.',
     'Auditoria /clientes 06/07/2026');
  END IF;
END $$;
